### ISSUE TITLE
如何获取用户id？

### ISSUE THREAD

**Issue by sunlanchang** [thunderhit/weibo_crawler#1]
**您好，Google后我看到的方法都是获取自己的id没有获取他人id的方法，请问如何获取某个特定用户的id呢？**

**Comment by thunderhit** [comment]
可以先登录微博看看自己的id是什么样子，然后再看看别人的id是什么样子，类比着即可。
对了，用户id一般是数字，等下我更新一下github仓库

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年5月5日(周三) 晚上10:05
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [thunderhit/weibo_crawler] 如何获取用户id？ (#1)




 
您好，Google后我看到的方法都是获取自己的id没有获取他人id的方法，请问如何获取某个特定用户的id呢？

**Comment by sunlanchang** [comment]
It works, thanks very much!
